/// Flutter icons Gmail
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Gmail
///      fonts:
///       - asset: fonts/Gmail.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Gmail {
  Gmail._();

  static const _kFontFam = 'Gmail';
  static const _kFontPkg = null;

  static const IconData gmail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
