/// Flutter icons NavBar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBar
///      fonts:
///       - asset: fonts/NavBar.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///
import 'package:flutter/widgets.dart';

class NavBar {
  NavBar._();

  static const _kFontFam = 'NavBar';
  static const _kFontPkg = null;

  static const IconData gmail = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiverr = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
